apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-mon
  namespace: default
  labels:
    release: prometheus
spec:
  endpoints:
    - port: http
      interval: 10s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: scaletestapp