@startuml C2_NovaMarket
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Контейнерная диаграмма NovaMarket

'Акторы
Person(buyer, "Покупатель", "Делает заказ, отменяет заказ")
Person(seller, "Продавец", "Предоставляет товары")

Container(buyerMobileApp, "Мобильное приложение покупателя", "", "Интерфейс для покупателей")
Container(sellerMobileApp, "Мобильное приложение продавца", "", "Интерфейс для продавцов")

System_Ext(paymentGateways, "Платёжные шлюзы", "Стандартный провайдеры платежей")
System_Ext(logisticsCompanies, "Логистические компании", "Службы доставки")

'Граница облачной системы
System_Boundary(cloud_system, "Backend NovaMarket") {
  Container(apiGateway, "API Gateway", "Nginx", "")

  Container(shoppingCartService, "Stock Service", "", "")
  Container(orderService, "Order Service", "", "")
  Container(paymentService, "Payment Service", "", "")
  Container(deliveryService, "Delivery Service", "", "")
  Container(notificationService, "Notification Service", "", "")

  ContainerQueue(kafka, "Event Broker (Bus)", "Kafka", "События EDA/SAGA")
}

'СВЯЗИ
'Пользователи -> Приложения
Rel(buyer, buyerMobileApp, "Выбор товаров, управление заказами")
Rel(seller, sellerMobileApp, "Предложение товаров, обработка заказов")

'Приложения -> API
Rel(buyerMobileApp, apiGateway, "REST")
Rel(sellerMobileApp, apiGateway, "REST")

'API -> микросервисы
Rel(apiGateway, shoppingCartService, "REST")
Rel(apiGateway, orderService, "REST")
Rel(apiGateway, paymentService, "REST")
Rel(notificationService, apiGateway, "REST")

'Нотификации
Rel(notificationService, buyerMobileApp, "ServerPush/WebSocke")
Rel(notificationService, sellerMobileApp, "ServerPush/WebSocke")

'Интеграции
Rel(paymentService, paymentGateways, "")
Rel(logisticsCompanies, deliveryService, "")
Rel(notificationService, logisticsCompanies, "")

@enduml